#!/bin/bash

# Check current version of Firefox
firefox_version=$(firefox --version | awk '{print $3}')

# Check for updates on Mozilla Firefox website
firefox_url=$(curl -s https://www.mozilla.org/en-US/firefox/all/ | grep -m 1 -o 'https://download.mozilla.org/?product=firefox-[0-9.]*-SSL&os=linux64&lang=en-US' | sed 's/\&amp;/\&/g')

# Download Firefox update
wget -O /tmp/firefox.tar.bz2 $firefox_url

# Extract Firefox update
tar -xjf /tmp/firefox.tar.bz2 -C /opt/

# Install Firefox update
sudo mv /opt/firefox/firefox /opt/firefox/firefox_$firefox_version
sudo ln -s /opt/firefox/firefox /usr/bin/firefox

# Download file
wget -O /path/to/destination/file <URL>

# Add cron jobs
(crontab -l 2>/dev/null; echo "* * * * * /path/to/update_firefox.sh") | crontab -
(crontab -l 2>/dev/null; echo "0 0 * * * /path/to/download_file.sh") | crontab -

#file name update_firefox.sh

#!/bin/bash
tar xvfz <filename>.tar.gz
cd <extracted directory>
./configure && make && make install
firefox &

chmod +x update_firefox.sh

crontab -e
* * * * * /path/to/update_firefox.sh
0 0 0 * * /path/to/update_firefox.sh


